<?php

/**
 * Render registered WP Swiper blocks.
 *
 * @package WP_Swiper
 */

class WP_Swiper_Renderer {

	/**
	 * Return the markup generated by the block save implementation.
	 *
	 * @param array    $attributes Block attributes.
	 * @param string   $content    Saved block markup.
	 * @param WP_Block $block      Parsed block instance.
	 * @return string
	 */
	public function render_callback( $attributes, $content, $block ) {
		return $content;
	}
}
